name       : xfce4-whiskermenu-plugin
version    : 2.7.3
release    : 1
source     :
    - https://archive.xfce.org/src/panel-plugins/xfce4-whiskermenu-plugin/2.7/xfce4-whiskermenu-plugin-2.7.3.tar.bz2 : da2699ec9665388cf7fa1090088290f78245667fa6846ffca14116264a9fe6e9
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : Alternate Xfce menu. 
description: |
    Alternate Xfce menu.
builddeps  :
    - pkgconfig(exo-2)
    - pkgconfig(garcon-1)
    - pkgconfig(libxfce4panel-2.0)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
